### Create a patient
POST http://localhost:8080/api/patients
Content-Type: application/json

{
    "firstName": "Jean",
    "lastName": "Dupont",
    "birthdate": "1990-05-15",
    "phoneNumber": "514-123-4567",
    "email": "jean.dupont@email.com"
}

### Get all patients
GET http://localhost:8080/api/patients

### Get patient by ID
GET http://localhost:8080/api/patients/?UUID?

### Delete a patient
DELETE http://localhost:8080/api/patients/?UUID?